filter: Work around gcc-7 warning noexcept-type
Full warning text:

error: mangled name for
std::vector<std::__cxx11::basic_string<char> > split(const char*,
Pred) [with Pred = int (*)(int) throw ()]
will change in C++17 because the exception specification is part of
a function type [-Werror=noexcept-type]

This warning does not seem very useful :-/ for now work around it by
using a lambda instead of isspace (that has throw() specifier).